export interface EquipmentStats {
  hpBase: number;
  hpPerTier: number;
  manaBase: number;
  manaPerTier: number;
  critBase: number;
  critPerTier: number;
  blockBase: number;
  blockPerTier: number;
  defenseBase: number;
  defensePerTier: number;
}

export interface EquipmentItem {
  id: string;
  name: string;
  type: "Helm" | "Shoulder" | "Chest" | "Hands" | "Feet" | "Ring" | "Necklace" | "Relic" | "Offhand";
  material: "Cloth" | "Leather" | "Metal" | "Gem";
  lore: string;
  stats: EquipmentStats;
  passive: string;
  attribute: string;
  effect: string;
  proc: string;
  setBonus: string;
}

function parseStats(hp: string, mana: string, crit: string, block: string, defense: string): EquipmentStats {
  const parse = (s: string) => {
    const [base, perTier] = s.split(" +").map(n => parseFloat(n) || 0);
    return { base, perTier };
  };
  return {
    hpBase: parse(hp).base,
    hpPerTier: parse(hp).perTier,
    manaBase: parse(mana).base,
    manaPerTier: parse(mana).perTier,
    critBase: parse(crit).base,
    critPerTier: parse(crit).perTier,
    blockBase: parse(block).base,
    blockPerTier: parse(block).perTier,
    defenseBase: parse(defense).base,
    defensePerTier: parse(defense).perTier,
  };
}

export const EQUIPMENT_SETS = ["Bloodfeud", "Wraithfang", "Oathbreaker", "Kinrend", "Dusksinger", "Emberclad"] as const;
export const EQUIPMENT_SLOTS = ["Helm", "Shoulder", "Chest", "Hands", "Feet", "Ring", "Necklace", "Relic"] as const;
export const ARMOR_MATERIALS = ["Cloth", "Leather", "Metal", "Gem"] as const;

export const CLOTH_EQUIPMENT: EquipmentItem[] = [
  { id: "cloth-bloodfeud-helm", name: "Bloodfeud Helm", type: "Helm", material: "Cloth", lore: "Forged in endless clan blood feuds", stats: parseStats("50 +10", "100 +21", "5 +0.5", "1 +0.1", "10 +2"), passive: "Mana Surge (+regen)", attribute: "+Int", effect: "Spell Amp (+5% magic dmg)", proc: "Mana Burst (10% restore mana)", setBonus: "Arcane Ward (group shield)" },
  { id: "cloth-wraithfang-helm", name: "Wraithfang Helm", type: "Helm", material: "Cloth", lore: "Whispers forgotten grudges in the dark", stats: parseStats("45 +9", "105 +22", "6 +0.6", "0.5 +0.05", "9 +1.8"), passive: "Shadow Veil (+stealth)", attribute: "+Wis", effect: "Evasion Boost (+dodge)", proc: "Shadow Fade (15% invis)", setBonus: "Wraith Echo (duplicate spell)" },
  { id: "cloth-oathbreaker-helm", name: "Oathbreaker Helm", type: "Helm", material: "Cloth", lore: "Breaks ancient oaths of peace", stats: parseStats("55 +11", "95 +20", "4 +0.4", "1.5 +0.15", "11 +2.2"), passive: "Purge Ward (+cleanse)", attribute: "+Int", effect: "Debuff Resist (+resist)", proc: "Oath Break (20% purge enemy)", setBonus: "Broken Oath (heal on purge)" },
  { id: "cloth-kinrend-helm", name: "Kinrend Helm", type: "Helm", material: "Cloth", lore: "Rends bonds of blood and kinship", stats: parseStats("52 +10.5", "98 +20.5", "5.5 +0.55", "1 +0.1", "10.5 +2.1"), passive: "Blood Link (+lifesteal)", attribute: "+Wis", effect: "Heal Amp (+healing)", proc: "Kin Bond (15% group heal)", setBonus: "Family Guard (shared shield)" },
  { id: "cloth-dusksinger-helm", name: "Dusksinger Helm", type: "Helm", material: "Cloth", lore: "Sings of twilight and ending grudges", stats: parseStats("48 +9.5", "102 +21.5", "4.5 +0.45", "0.8 +0.08", "9.5 +1.9"), passive: "Twilight Aura (+speed)", attribute: "+Int", effect: "Mobility Boost (+move)", proc: "Dusk Shift (10% teleport)", setBonus: "Evening Veil (AoE invis)" },
  { id: "cloth-emberclad-helm", name: "Emberclad Helm", type: "Helm", material: "Cloth", lore: "Clad in flames of burning hatred", stats: parseStats("53 +11", "97 +20", "5 +0.5", "1.2 +0.12", "10 +2"), passive: "Burn Ward (+fire resist)", attribute: "+Wis", effect: "DoT Amp (+DoT dmg)", proc: "Ember Proc (12% burn enemy)", setBonus: "Flame Cloak (reflect fire)" },
  { id: "cloth-bloodfeud-shoulder", name: "Bloodfeud Shoulder", type: "Shoulder", material: "Cloth", lore: "Forged in endless clan blood feuds", stats: parseStats("50 +10", "100 +21", "5 +0.5", "1 +0.1", "10 +2"), passive: "Mana Surge (+regen)", attribute: "+Int", effect: "Spell Amp (+5% magic dmg)", proc: "Mana Burst (10% restore mana)", setBonus: "Arcane Ward (group shield)" },
  { id: "cloth-wraithfang-shoulder", name: "Wraithfang Shoulder", type: "Shoulder", material: "Cloth", lore: "Whispers forgotten grudges in the dark", stats: parseStats("45 +9", "105 +22", "6 +0.6", "0.5 +0.05", "9 +1.8"), passive: "Shadow Veil (+stealth)", attribute: "+Wis", effect: "Evasion Boost (+dodge)", proc: "Shadow Fade (15% invis)", setBonus: "Wraith Echo (duplicate spell)" },
  { id: "cloth-oathbreaker-shoulder", name: "Oathbreaker Shoulder", type: "Shoulder", material: "Cloth", lore: "Breaks ancient oaths of peace", stats: parseStats("55 +11", "95 +20", "4 +0.4", "1.5 +0.15", "11 +2.2"), passive: "Purge Ward (+cleanse)", attribute: "+Int", effect: "Debuff Resist (+resist)", proc: "Oath Break (20% purge enemy)", setBonus: "Broken Oath (heal on purge)" },
  { id: "cloth-kinrend-shoulder", name: "Kinrend Shoulder", type: "Shoulder", material: "Cloth", lore: "Rends bonds of blood and kinship", stats: parseStats("52 +10.5", "98 +20.5", "5.5 +0.55", "1 +0.1", "10.5 +2.1"), passive: "Blood Link (+lifesteal)", attribute: "+Wis", effect: "Heal Amp (+healing)", proc: "Kin Bond (15% group heal)", setBonus: "Family Guard (shared shield)" },
  { id: "cloth-dusksinger-shoulder", name: "Dusksinger Shoulder", type: "Shoulder", material: "Cloth", lore: "Sings of twilight and ending grudges", stats: parseStats("48 +9.5", "102 +21.5", "4.5 +0.45", "0.8 +0.08", "9.5 +1.9"), passive: "Twilight Aura (+speed)", attribute: "+Int", effect: "Mobility Boost (+move)", proc: "Dusk Shift (10% teleport)", setBonus: "Evening Veil (AoE invis)" },
  { id: "cloth-emberclad-shoulder", name: "Emberclad Shoulder", type: "Shoulder", material: "Cloth", lore: "Clad in flames of burning hatred", stats: parseStats("53 +11", "97 +20", "5 +0.5", "1.2 +0.12", "10 +2"), passive: "Burn Ward (+fire resist)", attribute: "+Wis", effect: "DoT Amp (+DoT dmg)", proc: "Ember Proc (12% burn enemy)", setBonus: "Flame Cloak (reflect fire)" },
  { id: "cloth-bloodfeud-chest", name: "Bloodfeud Chest", type: "Chest", material: "Cloth", lore: "Forged in endless clan blood feuds", stats: parseStats("60 +12", "120 +25", "6 +0.6", "2 +0.2", "12 +2.5"), passive: "Mana Surge (+regen)", attribute: "+Int", effect: "Spell Amp (+5% magic dmg)", proc: "Mana Burst (10% restore mana)", setBonus: "Arcane Ward (group shield)" },
  { id: "cloth-wraithfang-chest", name: "Wraithfang Chest", type: "Chest", material: "Cloth", lore: "Whispers forgotten grudges in the dark", stats: parseStats("55 +11", "125 +26", "7 +0.7", "1.5 +0.15", "11 +2.2"), passive: "Shadow Veil (+stealth)", attribute: "+Wis", effect: "Evasion Boost (+dodge)", proc: "Shadow Fade (15% invis)", setBonus: "Wraith Echo (duplicate spell)" },
  { id: "cloth-oathbreaker-chest", name: "Oathbreaker Chest", type: "Chest", material: "Cloth", lore: "Breaks ancient oaths of peace", stats: parseStats("65 +13", "115 +24", "5 +0.5", "2.5 +0.25", "13 +2.6"), passive: "Purge Ward (+cleanse)", attribute: "+Int", effect: "Debuff Resist (+resist)", proc: "Oath Break (20% purge enemy)", setBonus: "Broken Oath (heal on purge)" },
  { id: "cloth-kinrend-chest", name: "Kinrend Chest", type: "Chest", material: "Cloth", lore: "Rends bonds of blood and kinship", stats: parseStats("62 +12.5", "118 +24.5", "6.5 +0.65", "2 +0.2", "12.5 +2.5"), passive: "Blood Link (+lifesteal)", attribute: "+Wis", effect: "Heal Amp (+healing)", proc: "Kin Bond (15% group heal)", setBonus: "Family Guard (shared shield)" },
  { id: "cloth-dusksinger-chest", name: "Dusksinger Chest", type: "Chest", material: "Cloth", lore: "Sings of twilight and ending grudges", stats: parseStats("58 +11.5", "122 +25.5", "5.5 +0.55", "1.8 +0.18", "11.5 +2.3"), passive: "Twilight Aura (+speed)", attribute: "+Int", effect: "Mobility Boost (+move)", proc: "Dusk Shift (10% teleport)", setBonus: "Evening Veil (AoE invis)" },
  { id: "cloth-emberclad-chest", name: "Emberclad Chest", type: "Chest", material: "Cloth", lore: "Clad in flames of burning hatred", stats: parseStats("63 +12.5", "117 +24.5", "6 +0.6", "2.2 +0.22", "12 +2.5"), passive: "Burn Ward (+fire resist)", attribute: "+Wis", effect: "DoT Amp (+DoT dmg)", proc: "Ember Proc (12% burn enemy)", setBonus: "Flame Cloak (reflect fire)" },
  { id: "cloth-bloodfeud-hands", name: "Bloodfeud Hands", type: "Hands", material: "Cloth", lore: "Forged in endless clan blood feuds", stats: parseStats("40 +8", "80 +17", "4 +0.4", "0.8 +0.08", "8 +1.6"), passive: "Mana Surge (+regen)", attribute: "+Int", effect: "Spell Amp (+5% magic dmg)", proc: "Mana Burst (10% restore mana)", setBonus: "Arcane Ward (group shield)" },
  { id: "cloth-wraithfang-hands", name: "Wraithfang Hands", type: "Hands", material: "Cloth", lore: "Whispers forgotten grudges in the dark", stats: parseStats("35 +7", "85 +18", "5 +0.5", "0.3 +0.03", "7 +1.4"), passive: "Shadow Veil (+stealth)", attribute: "+Wis", effect: "Evasion Boost (+dodge)", proc: "Shadow Fade (15% invis)", setBonus: "Wraith Echo (duplicate spell)" },
  { id: "cloth-oathbreaker-hands", name: "Oathbreaker Hands", type: "Hands", material: "Cloth", lore: "Breaks ancient oaths of peace", stats: parseStats("45 +9", "75 +16", "3 +0.3", "1.3 +0.13", "9 +1.8"), passive: "Purge Ward (+cleanse)", attribute: "+Int", effect: "Debuff Resist (+resist)", proc: "Oath Break (20% purge enemy)", setBonus: "Broken Oath (heal on purge)" },
  { id: "cloth-kinrend-hands", name: "Kinrend Hands", type: "Hands", material: "Cloth", lore: "Rends bonds of blood and kinship", stats: parseStats("42 +8.5", "78 +16.5", "4.5 +0.45", "0.8 +0.08", "8.5 +1.7"), passive: "Blood Link (+lifesteal)", attribute: "+Wis", effect: "Heal Amp (+healing)", proc: "Kin Bond (15% group heal)", setBonus: "Family Guard (shared shield)" },
  { id: "cloth-dusksinger-hands", name: "Dusksinger Hands", type: "Hands", material: "Cloth", lore: "Sings of twilight and ending grudges", stats: parseStats("38 +7.5", "82 +17.5", "3.5 +0.35", "0.6 +0.06", "7.5 +1.5"), passive: "Twilight Aura (+speed)", attribute: "+Int", effect: "Mobility Boost (+move)", proc: "Dusk Shift (10% teleport)", setBonus: "Evening Veil (AoE invis)" },
  { id: "cloth-emberclad-hands", name: "Emberclad Hands", type: "Hands", material: "Cloth", lore: "Clad in flames of burning hatred", stats: parseStats("43 +8.5", "77 +16.5", "4 +0.4", "1 +0.1", "8 +1.6"), passive: "Burn Ward (+fire resist)", attribute: "+Wis", effect: "DoT Amp (+DoT dmg)", proc: "Ember Proc (12% burn enemy)", setBonus: "Flame Cloak (reflect fire)" },
  { id: "cloth-bloodfeud-feet", name: "Bloodfeud Feet", type: "Feet", material: "Cloth", lore: "Forged in endless clan blood feuds", stats: parseStats("45 +9", "90 +19", "4.5 +0.45", "0.9 +0.09", "9 +1.8"), passive: "Mana Surge (+regen)", attribute: "+Int", effect: "Spell Amp (+5% magic dmg)", proc: "Mana Burst (10% restore mana)", setBonus: "Arcane Ward (group shield)" },
  { id: "cloth-wraithfang-feet", name: "Wraithfang Feet", type: "Feet", material: "Cloth", lore: "Whispers forgotten grudges in the dark", stats: parseStats("40 +8", "95 +20", "5.5 +0.55", "0.4 +0.04", "8 +1.6"), passive: "Shadow Veil (+stealth)", attribute: "+Wis", effect: "Evasion Boost (+dodge)", proc: "Shadow Fade (15% invis)", setBonus: "Wraith Echo (duplicate spell)" },
  { id: "cloth-oathbreaker-feet", name: "Oathbreaker Feet", type: "Feet", material: "Cloth", lore: "Breaks ancient oaths of peace", stats: parseStats("50 +10", "85 +18", "3.5 +0.35", "1.4 +0.14", "10 +2"), passive: "Purge Ward (+cleanse)", attribute: "+Int", effect: "Debuff Resist (+resist)", proc: "Oath Break (20% purge enemy)", setBonus: "Broken Oath (heal on purge)" },
  { id: "cloth-kinrend-feet", name: "Kinrend Feet", type: "Feet", material: "Cloth", lore: "Rends bonds of blood and kinship", stats: parseStats("47 +9.5", "88 +18.5", "5 +0.5", "0.9 +0.09", "9.5 +1.9"), passive: "Blood Link (+lifesteal)", attribute: "+Wis", effect: "Heal Amp (+healing)", proc: "Kin Bond (15% group heal)", setBonus: "Family Guard (shared shield)" },
  { id: "cloth-dusksinger-feet", name: "Dusksinger Feet", type: "Feet", material: "Cloth", lore: "Sings of twilight and ending grudges", stats: parseStats("43 +8.5", "92 +19.5", "4 +0.4", "0.7 +0.07", "8.5 +1.7"), passive: "Twilight Aura (+speed)", attribute: "+Int", effect: "Mobility Boost (+move)", proc: "Dusk Shift (10% teleport)", setBonus: "Evening Veil (AoE invis)" },
  { id: "cloth-emberclad-feet", name: "Emberclad Feet", type: "Feet", material: "Cloth", lore: "Clad in flames of burning hatred", stats: parseStats("48 +9.5", "87 +18.5", "4.5 +0.45", "1.1 +0.11", "9 +1.8"), passive: "Burn Ward (+fire resist)", attribute: "+Wis", effect: "DoT Amp (+DoT dmg)", proc: "Ember Proc (12% burn enemy)", setBonus: "Flame Cloak (reflect fire)" },
  { id: "cloth-bloodfeud-ring", name: "Bloodfeud Ring", type: "Ring", material: "Cloth", lore: "Forged in endless clan blood feuds", stats: parseStats("25 +5", "50 +11", "2.5 +0.25", "0.5 +0.05", "5 +1"), passive: "Mana Surge (+regen)", attribute: "+Int", effect: "Spell Amp (+5% magic dmg)", proc: "Mana Burst (10% restore mana)", setBonus: "Arcane Ward (group shield)" },
  { id: "cloth-wraithfang-ring", name: "Wraithfang Ring", type: "Ring", material: "Cloth", lore: "Whispers forgotten grudges in the dark", stats: parseStats("22.5 +4.5", "52.5 +11.5", "3 +0.3", "0.25 +0.025", "4.5 +0.9"), passive: "Shadow Veil (+stealth)", attribute: "+Wis", effect: "Evasion Boost (+dodge)", proc: "Shadow Fade (15% invis)", setBonus: "Wraith Echo (duplicate spell)" },
  { id: "cloth-oathbreaker-ring", name: "Oathbreaker Ring", type: "Ring", material: "Cloth", lore: "Breaks ancient oaths of peace", stats: parseStats("27.5 +5.5", "47.5 +10.5", "2 +0.2", "0.75 +0.075", "5.5 +1.1"), passive: "Purge Ward (+cleanse)", attribute: "+Int", effect: "Debuff Resist (+resist)", proc: "Oath Break (20% purge enemy)", setBonus: "Broken Oath (heal on purge)" },
  { id: "cloth-kinrend-ring", name: "Kinrend Ring", type: "Ring", material: "Cloth", lore: "Rends bonds of blood and kinship", stats: parseStats("26 +5.25", "49 +10.75", "2.75 +0.275", "0.5 +0.05", "5.25 +1.05"), passive: "Blood Link (+lifesteal)", attribute: "+Wis", effect: "Heal Amp (+healing)", proc: "Kin Bond (15% group heal)", setBonus: "Family Guard (shared shield)" },
  { id: "cloth-dusksinger-ring", name: "Dusksinger Ring", type: "Ring", material: "Cloth", lore: "Sings of twilight and ending grudges", stats: parseStats("24 +4.75", "51 +11.25", "2.25 +0.225", "0.4 +0.04", "4.75 +0.95"), passive: "Twilight Aura (+speed)", attribute: "+Int", effect: "Mobility Boost (+move)", proc: "Dusk Shift (10% teleport)", setBonus: "Evening Veil (AoE invis)" },
  { id: "cloth-emberclad-ring", name: "Emberclad Ring", type: "Ring", material: "Cloth", lore: "Clad in flames of burning hatred", stats: parseStats("26.5 +5.25", "48.5 +10.75", "2.5 +0.25", "0.6 +0.06", "5 +1"), passive: "Burn Ward (+fire resist)", attribute: "+Wis", effect: "DoT Amp (+DoT dmg)", proc: "Ember Proc (12% burn enemy)", setBonus: "Flame Cloak (reflect fire)" },
  { id: "cloth-bloodfeud-necklace", name: "Bloodfeud Necklace", type: "Necklace", material: "Cloth", lore: "Forged in endless clan blood feuds", stats: parseStats("25 +5", "50 +11", "2.5 +0.25", "0.5 +0.05", "5 +1"), passive: "Mana Surge (+regen)", attribute: "+Int", effect: "Spell Amp (+5% magic dmg)", proc: "Mana Burst (10% restore mana)", setBonus: "Arcane Ward (group shield)" },
  { id: "cloth-wraithfang-necklace", name: "Wraithfang Necklace", type: "Necklace", material: "Cloth", lore: "Whispers forgotten grudges in the dark", stats: parseStats("22.5 +4.5", "52.5 +11.5", "3 +0.3", "0.25 +0.025", "4.5 +0.9"), passive: "Shadow Veil (+stealth)", attribute: "+Wis", effect: "Evasion Boost (+dodge)", proc: "Shadow Fade (15% invis)", setBonus: "Wraith Echo (duplicate spell)" },
  { id: "cloth-oathbreaker-necklace", name: "Oathbreaker Necklace", type: "Necklace", material: "Cloth", lore: "Breaks ancient oaths of peace", stats: parseStats("27.5 +5.5", "47.5 +10.5", "2 +0.2", "0.75 +0.075", "5.5 +1.1"), passive: "Purge Ward (+cleanse)", attribute: "+Int", effect: "Debuff Resist (+resist)", proc: "Oath Break (20% purge enemy)", setBonus: "Broken Oath (heal on purge)" },
  { id: "cloth-kinrend-necklace", name: "Kinrend Necklace", type: "Necklace", material: "Cloth", lore: "Rends bonds of blood and kinship", stats: parseStats("26 +5.25", "49 +10.75", "2.75 +0.275", "0.5 +0.05", "5.25 +1.05"), passive: "Blood Link (+lifesteal)", attribute: "+Wis", effect: "Heal Amp (+healing)", proc: "Kin Bond (15% group heal)", setBonus: "Family Guard (shared shield)" },
  { id: "cloth-dusksinger-necklace", name: "Dusksinger Necklace", type: "Necklace", material: "Cloth", lore: "Sings of twilight and ending grudges", stats: parseStats("24 +4.75", "51 +11.25", "2.25 +0.225", "0.4 +0.04", "4.75 +0.95"), passive: "Twilight Aura (+speed)", attribute: "+Int", effect: "Mobility Boost (+move)", proc: "Dusk Shift (10% teleport)", setBonus: "Evening Veil (AoE invis)" },
  { id: "cloth-emberclad-necklace", name: "Emberclad Necklace", type: "Necklace", material: "Cloth", lore: "Clad in flames of burning hatred", stats: parseStats("26.5 +5.25", "48.5 +10.75", "2.5 +0.25", "0.6 +0.06", "5 +1"), passive: "Burn Ward (+fire resist)", attribute: "+Wis", effect: "DoT Amp (+DoT dmg)", proc: "Ember Proc (12% burn enemy)", setBonus: "Flame Cloak (reflect fire)" },
  { id: "cloth-bloodfeud-relic", name: "Bloodfeud Relic", type: "Relic", material: "Cloth", lore: "Forged in endless clan blood feuds", stats: parseStats("25 +5", "50 +11", "2.5 +0.25", "0.5 +0.05", "5 +1"), passive: "Mana Surge (+regen)", attribute: "+Int", effect: "Spell Amp (+5% magic dmg)", proc: "Mana Burst (10% restore mana)", setBonus: "Arcane Ward (group shield)" },
  { id: "cloth-wraithfang-relic", name: "Wraithfang Relic", type: "Relic", material: "Cloth", lore: "Whispers forgotten grudges in the dark", stats: parseStats("22.5 +4.5", "52.5 +11.5", "3 +0.3", "0.25 +0.025", "4.5 +0.9"), passive: "Shadow Veil (+stealth)", attribute: "+Wis", effect: "Evasion Boost (+dodge)", proc: "Shadow Fade (15% invis)", setBonus: "Wraith Echo (duplicate spell)" },
  { id: "cloth-oathbreaker-relic", name: "Oathbreaker Relic", type: "Relic", material: "Cloth", lore: "Breaks ancient oaths of peace", stats: parseStats("27.5 +5.5", "47.5 +10.5", "2 +0.2", "0.75 +0.075", "5.5 +1.1"), passive: "Purge Ward (+cleanse)", attribute: "+Int", effect: "Debuff Resist (+resist)", proc: "Oath Break (20% purge enemy)", setBonus: "Broken Oath (heal on purge)" },
  { id: "cloth-kinrend-relic", name: "Kinrend Relic", type: "Relic", material: "Cloth", lore: "Rends bonds of blood and kinship", stats: parseStats("26 +5.25", "49 +10.75", "2.75 +0.275", "0.5 +0.05", "5.25 +1.05"), passive: "Blood Link (+lifesteal)", attribute: "+Wis", effect: "Heal Amp (+healing)", proc: "Kin Bond (15% group heal)", setBonus: "Family Guard (shared shield)" },
  { id: "cloth-dusksinger-relic", name: "Dusksinger Relic", type: "Relic", material: "Cloth", lore: "Sings of twilight and ending grudges", stats: parseStats("24 +4.75", "51 +11.25", "2.25 +0.225", "0.4 +0.04", "4.75 +0.95"), passive: "Twilight Aura (+speed)", attribute: "+Int", effect: "Mobility Boost (+move)", proc: "Dusk Shift (10% teleport)", setBonus: "Evening Veil (AoE invis)" },
  { id: "cloth-emberclad-relic", name: "Emberclad Relic", type: "Relic", material: "Cloth", lore: "Clad in flames of burning hatred", stats: parseStats("26.5 +5.25", "48.5 +10.75", "2.5 +0.25", "0.6 +0.06", "5 +1"), passive: "Burn Ward (+fire resist)", attribute: "+Wis", effect: "DoT Amp (+DoT dmg)", proc: "Ember Proc (12% burn enemy)", setBonus: "Flame Cloak (reflect fire)" },
];

export const LEATHER_EQUIPMENT: EquipmentItem[] = [
  { id: "leather-bloodfeud-helm", name: "Bloodfeud Helm", type: "Helm", material: "Leather", lore: "Forged in endless clan blood feuds", stats: parseStats("80 +16", "50 +10", "6 +0.6", "3 +0.3", "20 +4"), passive: "Leather Stealth (+evade)", attribute: "+Dex", effect: "Speed Boost (+move)", proc: "Evade Proc (15% dodge)", setBonus: "Rogue Set (invis on crit)" },
  { id: "leather-wraithfang-helm", name: "Wraithfang Helm", type: "Helm", material: "Leather", lore: "Whispers forgotten grudges in the dark", stats: parseStats("75 +15", "55 +11", "7 +0.7", "2.5 +0.25", "19 +3.8"), passive: "Shadow Cloak (+stealth)", attribute: "+Agi", effect: "Crit Amp (+crit dmg)", proc: "Shadow Strike (10% backstab)", setBonus: "Phantom Set (teleport on low HP)" },
  { id: "leather-oathbreaker-helm", name: "Oathbreaker Helm", type: "Helm", material: "Leather", lore: "Breaks ancient oaths of peace", stats: parseStats("85 +17", "45 +9", "5 +0.5", "3.5 +0.35", "21 +4.2"), passive: "Purge Leather (+cleanse)", attribute: "+Dex", effect: "Debuff Boost (+debuff dur)", proc: "Oath Proc (12% purge)", setBonus: "Breaker Set (amp dmg on purged)" },
  { id: "leather-kinrend-helm", name: "Kinrend Helm", type: "Helm", material: "Leather", lore: "Rends bonds of blood and kinship", stats: parseStats("82 +16.5", "48 +9.5", "6.5 +0.65", "3 +0.3", "20.5 +4.1"), passive: "Blood Leather (+lifesteal)", attribute: "+Agi", effect: "Heal Boost (+self heal)", proc: "Kin Proc (14% heal on hit)", setBonus: "Family Set (group buff share)" },
  { id: "leather-dusksinger-helm", name: "Dusksinger Helm", type: "Helm", material: "Leather", lore: "Sings of twilight and ending grudges", stats: parseStats("78 +15.5", "52 +10.5", "5.5 +0.55", "2.8 +0.28", "19.5 +3.9"), passive: "Twilight Leather (+speed)", attribute: "+Dex", effect: "Mobility Amp (+dash)", proc: "Dusk Proc (11% speed burst)", setBonus: "Evening Set (AoE speed aura)" },
  { id: "leather-emberclad-helm", name: "Emberclad Helm", type: "Helm", material: "Leather", lore: "Clad in flames of burning hatred", stats: parseStats("83 +16.5", "47 +9.5", "6 +0.6", "3.2 +0.32", "20 +4"), passive: "Burn Leather (+fire resist)", attribute: "+Agi", effect: "DoT Boost (+DoT dur)", proc: "Ember Proc (13% burn)", setBonus: "Flame Set (reflect on block)" },
  { id: "leather-bloodfeud-shoulder", name: "Bloodfeud Shoulder", type: "Shoulder", material: "Leather", lore: "Forged in endless clan blood feuds", stats: parseStats("80 +16", "50 +10", "6 +0.6", "3 +0.3", "20 +4"), passive: "Leather Stealth (+evade)", attribute: "+Dex", effect: "Speed Boost (+move)", proc: "Evade Proc (15% dodge)", setBonus: "Rogue Set (invis on crit)" },
  { id: "leather-wraithfang-shoulder", name: "Wraithfang Shoulder", type: "Shoulder", material: "Leather", lore: "Whispers forgotten grudges in the dark", stats: parseStats("75 +15", "55 +11", "7 +0.7", "2.5 +0.25", "19 +3.8"), passive: "Shadow Cloak (+stealth)", attribute: "+Agi", effect: "Crit Amp (+crit dmg)", proc: "Shadow Strike (10% backstab)", setBonus: "Phantom Set (teleport on low HP)" },
  { id: "leather-oathbreaker-shoulder", name: "Oathbreaker Shoulder", type: "Shoulder", material: "Leather", lore: "Breaks ancient oaths of peace", stats: parseStats("85 +17", "45 +9", "5 +0.5", "3.5 +0.35", "21 +4.2"), passive: "Purge Leather (+cleanse)", attribute: "+Dex", effect: "Debuff Boost (+debuff dur)", proc: "Oath Proc (12% purge)", setBonus: "Breaker Set (amp dmg on purged)" },
  { id: "leather-kinrend-shoulder", name: "Kinrend Shoulder", type: "Shoulder", material: "Leather", lore: "Rends bonds of blood and kinship", stats: parseStats("82 +16.5", "48 +9.5", "6.5 +0.65", "3 +0.3", "20.5 +4.1"), passive: "Blood Leather (+lifesteal)", attribute: "+Agi", effect: "Heal Boost (+self heal)", proc: "Kin Proc (14% heal on hit)", setBonus: "Family Set (group buff share)" },
  { id: "leather-dusksinger-shoulder", name: "Dusksinger Shoulder", type: "Shoulder", material: "Leather", lore: "Sings of twilight and ending grudges", stats: parseStats("78 +15.5", "52 +10.5", "5.5 +0.55", "2.8 +0.28", "19.5 +3.9"), passive: "Twilight Leather (+speed)", attribute: "+Dex", effect: "Mobility Amp (+dash)", proc: "Dusk Proc (11% speed burst)", setBonus: "Evening Set (AoE speed aura)" },
  { id: "leather-emberclad-shoulder", name: "Emberclad Shoulder", type: "Shoulder", material: "Leather", lore: "Clad in flames of burning hatred", stats: parseStats("83 +16.5", "47 +9.5", "6 +0.6", "3.2 +0.32", "20 +4"), passive: "Burn Leather (+fire resist)", attribute: "+Agi", effect: "DoT Boost (+DoT dur)", proc: "Ember Proc (13% burn)", setBonus: "Flame Set (reflect on block)" },
  { id: "leather-bloodfeud-chest", name: "Bloodfeud Chest", type: "Chest", material: "Leather", lore: "Forged in endless clan blood feuds", stats: parseStats("90 +18", "60 +12", "7 +0.7", "4 +0.4", "22 +4.5"), passive: "Leather Stealth (+evade)", attribute: "+Dex", effect: "Speed Boost (+move)", proc: "Evade Proc (15% dodge)", setBonus: "Rogue Set (invis on crit)" },
  { id: "leather-wraithfang-chest", name: "Wraithfang Chest", type: "Chest", material: "Leather", lore: "Whispers forgotten grudges in the dark", stats: parseStats("85 +17", "65 +13", "8 +0.8", "3.5 +0.35", "21 +4.2"), passive: "Shadow Cloak (+stealth)", attribute: "+Agi", effect: "Crit Amp (+crit dmg)", proc: "Shadow Strike (10% backstab)", setBonus: "Phantom Set (teleport on low HP)" },
  { id: "leather-oathbreaker-chest", name: "Oathbreaker Chest", type: "Chest", material: "Leather", lore: "Breaks ancient oaths of peace", stats: parseStats("95 +19", "55 +11", "6 +0.6", "4.5 +0.45", "23 +4.6"), passive: "Purge Leather (+cleanse)", attribute: "+Dex", effect: "Debuff Boost (+debuff dur)", proc: "Oath Proc (12% purge)", setBonus: "Breaker Set (amp dmg on purged)" },
  { id: "leather-kinrend-chest", name: "Kinrend Chest", type: "Chest", material: "Leather", lore: "Rends bonds of blood and kinship", stats: parseStats("92 +18.5", "58 +11.5", "7.5 +0.75", "4 +0.4", "22.5 +4.5"), passive: "Blood Leather (+lifesteal)", attribute: "+Agi", effect: "Heal Boost (+self heal)", proc: "Kin Proc (14% heal on hit)", setBonus: "Family Set (group buff share)" },
  { id: "leather-dusksinger-chest", name: "Dusksinger Chest", type: "Chest", material: "Leather", lore: "Sings of twilight and ending grudges", stats: parseStats("88 +17.5", "62 +12.5", "6.5 +0.65", "3.8 +0.38", "21.5 +4.3"), passive: "Twilight Leather (+speed)", attribute: "+Dex", effect: "Mobility Amp (+dash)", proc: "Dusk Proc (11% speed burst)", setBonus: "Evening Set (AoE speed aura)" },
  { id: "leather-emberclad-chest", name: "Emberclad Chest", type: "Chest", material: "Leather", lore: "Clad in flames of burning hatred", stats: parseStats("93 +18.5", "57 +11.5", "7 +0.7", "4.2 +0.42", "22 +4.5"), passive: "Burn Leather (+fire resist)", attribute: "+Agi", effect: "DoT Boost (+DoT dur)", proc: "Ember Proc (13% burn)", setBonus: "Flame Set (reflect on block)" },
  { id: "leather-bloodfeud-hands", name: "Bloodfeud Hands", type: "Hands", material: "Leather", lore: "Forged in endless clan blood feuds", stats: parseStats("70 +14", "40 +8", "5 +0.5", "2.5 +0.25", "18 +3.6"), passive: "Leather Stealth (+evade)", attribute: "+Dex", effect: "Speed Boost (+move)", proc: "Evade Proc (15% dodge)", setBonus: "Rogue Set (invis on crit)" },
  { id: "leather-wraithfang-hands", name: "Wraithfang Hands", type: "Hands", material: "Leather", lore: "Whispers forgotten grudges in the dark", stats: parseStats("65 +13", "45 +9", "6 +0.6", "2 +0.2", "17 +3.4"), passive: "Shadow Cloak (+stealth)", attribute: "+Agi", effect: "Crit Amp (+crit dmg)", proc: "Shadow Strike (10% backstab)", setBonus: "Phantom Set (teleport on low HP)" },
  { id: "leather-oathbreaker-hands", name: "Oathbreaker Hands", type: "Hands", material: "Leather", lore: "Breaks ancient oaths of peace", stats: parseStats("75 +15", "35 +7", "4 +0.4", "3 +0.3", "19 +3.8"), passive: "Purge Leather (+cleanse)", attribute: "+Dex", effect: "Debuff Boost (+debuff dur)", proc: "Oath Proc (12% purge)", setBonus: "Breaker Set (amp dmg on purged)" },
  { id: "leather-kinrend-hands", name: "Kinrend Hands", type: "Hands", material: "Leather", lore: "Rends bonds of blood and kinship", stats: parseStats("72 +14.5", "38 +7.5", "5.5 +0.55", "2.5 +0.25", "18.5 +3.7"), passive: "Blood Leather (+lifesteal)", attribute: "+Agi", effect: "Heal Boost (+self heal)", proc: "Kin Proc (14% heal on hit)", setBonus: "Family Set (group buff share)" },
  { id: "leather-dusksinger-hands", name: "Dusksinger Hands", type: "Hands", material: "Leather", lore: "Sings of twilight and ending grudges", stats: parseStats("68 +13.5", "42 +8.5", "4.5 +0.45", "2.3 +0.23", "17.5 +3.5"), passive: "Twilight Leather (+speed)", attribute: "+Dex", effect: "Mobility Amp (+dash)", proc: "Dusk Proc (11% speed burst)", setBonus: "Evening Set (AoE speed aura)" },
  { id: "leather-emberclad-hands", name: "Emberclad Hands", type: "Hands", material: "Leather", lore: "Clad in flames of burning hatred", stats: parseStats("73 +14.5", "37 +7.5", "5 +0.5", "2.7 +0.27", "18 +3.6"), passive: "Burn Leather (+fire resist)", attribute: "+Agi", effect: "DoT Boost (+DoT dur)", proc: "Ember Proc (13% burn)", setBonus: "Flame Set (reflect on block)" },
  { id: "leather-bloodfeud-feet", name: "Bloodfeud Feet", type: "Feet", material: "Leather", lore: "Forged in endless clan blood feuds", stats: parseStats("75 +15", "45 +9", "5.5 +0.55", "2.8 +0.28", "19 +3.8"), passive: "Leather Stealth (+evade)", attribute: "+Dex", effect: "Speed Boost (+move)", proc: "Evade Proc (15% dodge)", setBonus: "Rogue Set (invis on crit)" },
  { id: "leather-wraithfang-feet", name: "Wraithfang Feet", type: "Feet", material: "Leather", lore: "Whispers forgotten grudges in the dark", stats: parseStats("70 +14", "50 +10", "6.5 +0.65", "2.3 +0.23", "18 +3.6"), passive: "Shadow Cloak (+stealth)", attribute: "+Agi", effect: "Crit Amp (+crit dmg)", proc: "Shadow Strike (10% backstab)", setBonus: "Phantom Set (teleport on low HP)" },
  { id: "leather-oathbreaker-feet", name: "Oathbreaker Feet", type: "Feet", material: "Leather", lore: "Breaks ancient oaths of peace", stats: parseStats("80 +16", "40 +8", "4.5 +0.45", "3.3 +0.33", "20 +4"), passive: "Purge Leather (+cleanse)", attribute: "+Dex", effect: "Debuff Boost (+debuff dur)", proc: "Oath Proc (12% purge)", setBonus: "Breaker Set (amp dmg on purged)" },
  { id: "leather-kinrend-feet", name: "Kinrend Feet", type: "Feet", material: "Leather", lore: "Rends bonds of blood and kinship", stats: parseStats("77 +15.5", "43 +8.5", "6 +0.6", "2.8 +0.28", "19.5 +3.9"), passive: "Blood Leather (+lifesteal)", attribute: "+Agi", effect: "Heal Boost (+self heal)", proc: "Kin Proc (14% heal on hit)", setBonus: "Family Set (group buff share)" },
  { id: "leather-dusksinger-feet", name: "Dusksinger Feet", type: "Feet", material: "Leather", lore: "Sings of twilight and ending grudges", stats: parseStats("73 +14.5", "47 +9.5", "5 +0.5", "2.6 +0.26", "18.5 +3.7"), passive: "Twilight Leather (+speed)", attribute: "+Dex", effect: "Mobility Amp (+dash)", proc: "Dusk Proc (11% speed burst)", setBonus: "Evening Set (AoE speed aura)" },
  { id: "leather-emberclad-feet", name: "Emberclad Feet", type: "Feet", material: "Leather", lore: "Clad in flames of burning hatred", stats: parseStats("78 +15.5", "42 +8.5", "5.5 +0.55", "3 +0.3", "19 +3.8"), passive: "Burn Leather (+fire resist)", attribute: "+Agi", effect: "DoT Boost (+DoT dur)", proc: "Ember Proc (13% burn)", setBonus: "Flame Set (reflect on block)" },
  { id: "leather-bloodfeud-ring", name: "Bloodfeud Ring", type: "Ring", material: "Leather", lore: "Forged in endless clan blood feuds", stats: parseStats("40 +8", "25 +5", "3 +0.3", "1.5 +0.15", "10 +2"), passive: "Leather Stealth (+evade)", attribute: "+Dex", effect: "Speed Boost (+move)", proc: "Evade Proc (15% dodge)", setBonus: "Rogue Set (invis on crit)" },
  { id: "leather-wraithfang-ring", name: "Wraithfang Ring", type: "Ring", material: "Leather", lore: "Whispers forgotten grudges in the dark", stats: parseStats("37.5 +7.5", "27.5 +5.5", "3.5 +0.35", "1.25 +0.125", "9.5 +1.9"), passive: "Shadow Cloak (+stealth)", attribute: "+Agi", effect: "Crit Amp (+crit dmg)", proc: "Shadow Strike (10% backstab)", setBonus: "Phantom Set (teleport on low HP)" },
  { id: "leather-oathbreaker-ring", name: "Oathbreaker Ring", type: "Ring", material: "Leather", lore: "Breaks ancient oaths of peace", stats: parseStats("42.5 +8.5", "22.5 +4.5", "2.5 +0.25", "1.75 +0.175", "10.5 +2.1"), passive: "Purge Leather (+cleanse)", attribute: "+Dex", effect: "Debuff Boost (+debuff dur)", proc: "Oath Proc (12% purge)", setBonus: "Breaker Set (amp dmg on purged)" },
  { id: "leather-kinrend-ring", name: "Kinrend Ring", type: "Ring", material: "Leather", lore: "Rends bonds of blood and kinship", stats: parseStats("41 +8.25", "24 +4.75", "3.25 +0.325", "1.5 +0.15", "10.25 +2.05"), passive: "Blood Leather (+lifesteal)", attribute: "+Agi", effect: "Heal Boost (+self heal)", proc: "Kin Proc (14% heal on hit)", setBonus: "Family Set (group buff share)" },
  { id: "leather-dusksinger-ring", name: "Dusksinger Ring", type: "Ring", material: "Leather", lore: "Sings of twilight and ending grudges", stats: parseStats("39 +7.75", "26 +5.25", "2.75 +0.275", "1.4 +0.14", "9.75 +1.95"), passive: "Twilight Leather (+speed)", attribute: "+Dex", effect: "Mobility Amp (+dash)", proc: "Dusk Proc (11% speed burst)", setBonus: "Evening Set (AoE speed aura)" },
  { id: "leather-emberclad-ring", name: "Emberclad Ring", type: "Ring", material: "Leather", lore: "Clad in flames of burning hatred", stats: parseStats("41.5 +8.25", "23.5 +4.75", "3 +0.3", "1.6 +0.16", "10 +2"), passive: "Burn Leather (+fire resist)", attribute: "+Agi", effect: "DoT Boost (+DoT dur)", proc: "Ember Proc (13% burn)", setBonus: "Flame Set (reflect on block)" },
  { id: "leather-bloodfeud-necklace", name: "Bloodfeud Necklace", type: "Necklace", material: "Leather", lore: "Forged in endless clan blood feuds", stats: parseStats("40 +8", "25 +5", "3 +0.3", "1.5 +0.15", "10 +2"), passive: "Leather Stealth (+evade)", attribute: "+Dex", effect: "Speed Boost (+move)", proc: "Evade Proc (15% dodge)", setBonus: "Rogue Set (invis on crit)" },
  { id: "leather-wraithfang-necklace", name: "Wraithfang Necklace", type: "Necklace", material: "Leather", lore: "Whispers forgotten grudges in the dark", stats: parseStats("37.5 +7.5", "27.5 +5.5", "3.5 +0.35", "1.25 +0.125", "9.5 +1.9"), passive: "Shadow Cloak (+stealth)", attribute: "+Agi", effect: "Crit Amp (+crit dmg)", proc: "Shadow Strike (10% backstab)", setBonus: "Phantom Set (teleport on low HP)" },
  { id: "leather-oathbreaker-necklace", name: "Oathbreaker Necklace", type: "Necklace", material: "Leather", lore: "Breaks ancient oaths of peace", stats: parseStats("42.5 +8.5", "22.5 +4.5", "2.5 +0.25", "1.75 +0.175", "10.5 +2.1"), passive: "Purge Leather (+cleanse)", attribute: "+Dex", effect: "Debuff Boost (+debuff dur)", proc: "Oath Proc (12% purge)", setBonus: "Breaker Set (amp dmg on purged)" },
  { id: "leather-kinrend-necklace", name: "Kinrend Necklace", type: "Necklace", material: "Leather", lore: "Rends bonds of blood and kinship", stats: parseStats("41 +8.25", "24 +4.75", "3.25 +0.325", "1.5 +0.15", "10.25 +2.05"), passive: "Blood Leather (+lifesteal)", attribute: "+Agi", effect: "Heal Boost (+self heal)", proc: "Kin Proc (14% heal on hit)", setBonus: "Family Set (group buff share)" },
  { id: "leather-dusksinger-necklace", name: "Dusksinger Necklace", type: "Necklace", material: "Leather", lore: "Sings of twilight and ending grudges", stats: parseStats("39 +7.75", "26 +5.25", "2.75 +0.275", "1.4 +0.14", "9.75 +1.95"), passive: "Twilight Leather (+speed)", attribute: "+Dex", effect: "Mobility Amp (+dash)", proc: "Dusk Proc (11% speed burst)", setBonus: "Evening Set (AoE speed aura)" },
  { id: "leather-emberclad-necklace", name: "Emberclad Necklace", type: "Necklace", material: "Leather", lore: "Clad in flames of burning hatred", stats: parseStats("41.5 +8.25", "23.5 +4.75", "3 +0.3", "1.6 +0.16", "10 +2"), passive: "Burn Leather (+fire resist)", attribute: "+Agi", effect: "DoT Boost (+DoT dur)", proc: "Ember Proc (13% burn)", setBonus: "Flame Set (reflect on block)" },
  { id: "leather-bloodfeud-relic", name: "Bloodfeud Relic", type: "Relic", material: "Leather", lore: "Forged in endless clan blood feuds", stats: parseStats("40 +8", "25 +5", "3 +0.3", "1.5 +0.15", "10 +2"), passive: "Leather Stealth (+evade)", attribute: "+Dex", effect: "Speed Boost (+move)", proc: "Evade Proc (15% dodge)", setBonus: "Rogue Set (invis on crit)" },
  { id: "leather-wraithfang-relic", name: "Wraithfang Relic", type: "Relic", material: "Leather", lore: "Whispers forgotten grudges in the dark", stats: parseStats("37.5 +7.5", "27.5 +5.5", "3.5 +0.35", "1.25 +0.125", "9.5 +1.9"), passive: "Shadow Cloak (+stealth)", attribute: "+Agi", effect: "Crit Amp (+crit dmg)", proc: "Shadow Strike (10% backstab)", setBonus: "Phantom Set (teleport on low HP)" },
  { id: "leather-oathbreaker-relic", name: "Oathbreaker Relic", type: "Relic", material: "Leather", lore: "Breaks ancient oaths of peace", stats: parseStats("42.5 +8.5", "22.5 +4.5", "2.5 +0.25", "1.75 +0.175", "10.5 +2.1"), passive: "Purge Leather (+cleanse)", attribute: "+Dex", effect: "Debuff Boost (+debuff dur)", proc: "Oath Proc (12% purge)", setBonus: "Breaker Set (amp dmg on purged)" },
  { id: "leather-kinrend-relic", name: "Kinrend Relic", type: "Relic", material: "Leather", lore: "Rends bonds of blood and kinship", stats: parseStats("41 +8.25", "24 +4.75", "3.25 +0.325", "1.5 +0.15", "10.25 +2.05"), passive: "Blood Leather (+lifesteal)", attribute: "+Agi", effect: "Heal Boost (+self heal)", proc: "Kin Proc (14% heal on hit)", setBonus: "Family Set (group buff share)" },
  { id: "leather-dusksinger-relic", name: "Dusksinger Relic", type: "Relic", material: "Leather", lore: "Sings of twilight and ending grudges", stats: parseStats("39 +7.75", "26 +5.25", "2.75 +0.275", "1.4 +0.14", "9.75 +1.95"), passive: "Twilight Leather (+speed)", attribute: "+Dex", effect: "Mobility Amp (+dash)", proc: "Dusk Proc (11% speed burst)", setBonus: "Evening Set (AoE speed aura)" },
  { id: "leather-emberclad-relic", name: "Emberclad Relic", type: "Relic", material: "Leather", lore: "Clad in flames of burning hatred", stats: parseStats("41.5 +8.25", "23.5 +4.75", "3 +0.3", "1.6 +0.16", "10 +2"), passive: "Burn Leather (+fire resist)", attribute: "+Agi", effect: "DoT Boost (+DoT dur)", proc: "Ember Proc (13% burn)", setBonus: "Flame Set (reflect on block)" },
];

export const METAL_EQUIPMENT: EquipmentItem[] = [
  { id: "metal-bloodfeud-helm", name: "Bloodfeud Helm", type: "Helm", material: "Metal", lore: "Forged in endless clan blood feuds", stats: parseStats("100 +21", "20 +4", "2 +0.2", "8 +0.8", "30 +6"), passive: "Tank Stance (+threat)", attribute: "+Vit", effect: "Armor Amp (+def)", proc: "Block Proc (20% reflect)", setBonus: "Guardian Set (AoE taunt)" },
  { id: "metal-wraithfang-helm", name: "Wraithfang Helm", type: "Helm", material: "Metal", lore: "Whispers forgotten grudges in the dark", stats: parseStats("95 +20", "25 +5", "3 +0.3", "7.5 +0.75", "29 +5.8"), passive: "Shadow Tank (+resist)", attribute: "+Str", effect: "Block Boost (+block dmg)", proc: "Wraith Proc (15% fear)", setBonus: "Phantom Set (absorb dmg)" },
  { id: "metal-oathbreaker-helm", name: "Oathbreaker Helm", type: "Helm", material: "Metal", lore: "Breaks ancient oaths of peace", stats: parseStats("105 +22", "15 +3", "1 +0.1", "8.5 +0.85", "31 +6.2"), passive: "Purge Metal (+cleanse)", attribute: "+Vit", effect: "Debuff Resist (+resist)", proc: "Oath Proc (18% purge)", setBonus: "Breaker Set (counter on block)" },
  { id: "metal-kinrend-helm", name: "Kinrend Helm", type: "Helm", material: "Metal", lore: "Rends bonds of blood and kinship", stats: parseStats("102 +21.5", "18 +3.5", "2.5 +0.25", "8 +0.8", "30.5 +6.1"), passive: "Blood Metal (+lifesteal)", attribute: "+Str", effect: "Heal Amp (+self heal)", proc: "Kin Proc (16% heal on block)", setBonus: "Family Set (group shield)" },
  { id: "metal-dusksinger-helm", name: "Dusksinger Helm", type: "Helm", material: "Metal", lore: "Sings of twilight and ending grudges", stats: parseStats("98 +20.5", "22 +4.5", "1.5 +0.15", "7.8 +0.78", "29.5 +5.9"), passive: "Twilight Metal (+speed)", attribute: "+Vit", effect: "Mobility Boost (+move)", proc: "Dusk Proc (13% speed burst)", setBonus: "Evening Set (AoE resist aura)" },
  { id: "metal-emberclad-helm", name: "Emberclad Helm", type: "Helm", material: "Metal", lore: "Clad in flames of burning hatred", stats: parseStats("103 +21.5", "17 +3.5", "2 +0.2", "8.2 +0.82", "30 +6"), passive: "Burn Metal (+fire resist)", attribute: "+Str", effect: "DoT Amp (+DoT dmg)", proc: "Ember Proc (14% burn)", setBonus: "Flame Set (reflect on hit)" },
  { id: "metal-bloodfeud-shoulder", name: "Bloodfeud Shoulder", type: "Shoulder", material: "Metal", lore: "Forged in endless clan blood feuds", stats: parseStats("100 +21", "20 +4", "2 +0.2", "8 +0.8", "30 +6"), passive: "Tank Stance (+threat)", attribute: "+Vit", effect: "Armor Amp (+def)", proc: "Block Proc (20% reflect)", setBonus: "Guardian Set (AoE taunt)" },
  { id: "metal-wraithfang-shoulder", name: "Wraithfang Shoulder", type: "Shoulder", material: "Metal", lore: "Whispers forgotten grudges in the dark", stats: parseStats("95 +20", "25 +5", "3 +0.3", "7.5 +0.75", "29 +5.8"), passive: "Shadow Tank (+resist)", attribute: "+Str", effect: "Block Boost (+block dmg)", proc: "Wraith Proc (15% fear)", setBonus: "Phantom Set (absorb dmg)" },
  { id: "metal-oathbreaker-shoulder", name: "Oathbreaker Shoulder", type: "Shoulder", material: "Metal", lore: "Breaks ancient oaths of peace", stats: parseStats("105 +22", "15 +3", "1 +0.1", "8.5 +0.85", "31 +6.2"), passive: "Purge Metal (+cleanse)", attribute: "+Vit", effect: "Debuff Resist (+resist)", proc: "Oath Proc (18% purge)", setBonus: "Breaker Set (counter on block)" },
  { id: "metal-kinrend-shoulder", name: "Kinrend Shoulder", type: "Shoulder", material: "Metal", lore: "Rends bonds of blood and kinship", stats: parseStats("102 +21.5", "18 +3.5", "2.5 +0.25", "8 +0.8", "30.5 +6.1"), passive: "Blood Metal (+lifesteal)", attribute: "+Str", effect: "Heal Amp (+self heal)", proc: "Kin Proc (16% heal on block)", setBonus: "Family Set (group shield)" },
  { id: "metal-dusksinger-shoulder", name: "Dusksinger Shoulder", type: "Shoulder", material: "Metal", lore: "Sings of twilight and ending grudges", stats: parseStats("98 +20.5", "22 +4.5", "1.5 +0.15", "7.8 +0.78", "29.5 +5.9"), passive: "Twilight Metal (+speed)", attribute: "+Vit", effect: "Mobility Boost (+move)", proc: "Dusk Proc (13% speed burst)", setBonus: "Evening Set (AoE resist aura)" },
  { id: "metal-emberclad-shoulder", name: "Emberclad Shoulder", type: "Shoulder", material: "Metal", lore: "Clad in flames of burning hatred", stats: parseStats("103 +21.5", "17 +3.5", "2 +0.2", "8.2 +0.82", "30 +6"), passive: "Burn Metal (+fire resist)", attribute: "+Str", effect: "DoT Amp (+DoT dmg)", proc: "Ember Proc (14% burn)", setBonus: "Flame Set (reflect on hit)" },
  { id: "metal-bloodfeud-chest", name: "Bloodfeud Chest", type: "Chest", material: "Metal", lore: "Forged in endless clan blood feuds", stats: parseStats("110 +23", "30 +6", "3 +0.3", "9 +0.9", "32 +6.5"), passive: "Tank Stance (+threat)", attribute: "+Vit", effect: "Armor Amp (+def)", proc: "Block Proc (20% reflect)", setBonus: "Guardian Set (AoE taunt)" },
  { id: "metal-wraithfang-chest", name: "Wraithfang Chest", type: "Chest", material: "Metal", lore: "Whispers forgotten grudges in the dark", stats: parseStats("105 +22", "35 +7", "4 +0.4", "8.5 +0.85", "31 +6.2"), passive: "Shadow Tank (+resist)", attribute: "+Str", effect: "Block Boost (+block dmg)", proc: "Wraith Proc (15% fear)", setBonus: "Phantom Set (absorb dmg)" },
  { id: "metal-oathbreaker-chest", name: "Oathbreaker Chest", type: "Chest", material: "Metal", lore: "Breaks ancient oaths of peace", stats: parseStats("115 +24", "25 +5", "2 +0.2", "9.5 +0.95", "33 +6.6"), passive: "Purge Metal (+cleanse)", attribute: "+Vit", effect: "Debuff Resist (+resist)", proc: "Oath Proc (18% purge)", setBonus: "Breaker Set (counter on block)" },
  { id: "metal-kinrend-chest", name: "Kinrend Chest", type: "Chest", material: "Metal", lore: "Rends bonds of blood and kinship", stats: parseStats("112 +23.5", "28 +5.5", "3.5 +0.35", "9 +0.9", "32.5 +6.5"), passive: "Blood Metal (+lifesteal)", attribute: "+Str", effect: "Heal Amp (+self heal)", proc: "Kin Proc (16% heal on block)", setBonus: "Family Set (group shield)" },
  { id: "metal-dusksinger-chest", name: "Dusksinger Chest", type: "Chest", material: "Metal", lore: "Sings of twilight and ending grudges", stats: parseStats("108 +22.5", "32 +6.5", "2.5 +0.25", "8.8 +0.88", "31.5 +6.3"), passive: "Twilight Metal (+speed)", attribute: "+Vit", effect: "Mobility Boost (+move)", proc: "Dusk Proc (13% speed burst)", setBonus: "Evening Set (AoE resist aura)" },
  { id: "metal-emberclad-chest", name: "Emberclad Chest", type: "Chest", material: "Metal", lore: "Clad in flames of burning hatred", stats: parseStats("113 +23.5", "27 +5.5", "3 +0.3", "9.2 +0.92", "32 +6.5"), passive: "Burn Metal (+fire resist)", attribute: "+Str", effect: "DoT Amp (+DoT dmg)", proc: "Ember Proc (14% burn)", setBonus: "Flame Set (reflect on hit)" },
  { id: "metal-bloodfeud-hands", name: "Bloodfeud Hands", type: "Hands", material: "Metal", lore: "Forged in endless clan blood feuds", stats: parseStats("80 +17", "15 +3", "1.5 +0.15", "6.5 +0.65", "25 +5"), passive: "Tank Stance (+threat)", attribute: "+Vit", effect: "Armor Amp (+def)", proc: "Block Proc (20% reflect)", setBonus: "Guardian Set (AoE taunt)" },
  { id: "metal-wraithfang-hands", name: "Wraithfang Hands", type: "Hands", material: "Metal", lore: "Whispers forgotten grudges in the dark", stats: parseStats("75 +16", "20 +4", "2.5 +0.25", "6 +0.6", "24 +4.8"), passive: "Shadow Tank (+resist)", attribute: "+Str", effect: "Block Boost (+block dmg)", proc: "Wraith Proc (15% fear)", setBonus: "Phantom Set (absorb dmg)" },
  { id: "metal-oathbreaker-hands", name: "Oathbreaker Hands", type: "Hands", material: "Metal", lore: "Breaks ancient oaths of peace", stats: parseStats("85 +18", "10 +2", "0.5 +0.05", "7 +0.7", "26 +5.2"), passive: "Purge Metal (+cleanse)", attribute: "+Vit", effect: "Debuff Resist (+resist)", proc: "Oath Proc (18% purge)", setBonus: "Breaker Set (counter on block)" },
  { id: "metal-kinrend-hands", name: "Kinrend Hands", type: "Hands", material: "Metal", lore: "Rends bonds of blood and kinship", stats: parseStats("82 +17.5", "13 +2.5", "2 +0.2", "6.5 +0.65", "25.5 +5.1"), passive: "Blood Metal (+lifesteal)", attribute: "+Str", effect: "Heal Amp (+self heal)", proc: "Kin Proc (16% heal on block)", setBonus: "Family Set (group shield)" },
  { id: "metal-dusksinger-hands", name: "Dusksinger Hands", type: "Hands", material: "Metal", lore: "Sings of twilight and ending grudges", stats: parseStats("78 +16.5", "17 +3.5", "1 +0.1", "6.3 +0.63", "24.5 +4.9"), passive: "Twilight Metal (+speed)", attribute: "+Vit", effect: "Mobility Boost (+move)", proc: "Dusk Proc (13% speed burst)", setBonus: "Evening Set (AoE resist aura)" },
  { id: "metal-emberclad-hands", name: "Emberclad Hands", type: "Hands", material: "Metal", lore: "Clad in flames of burning hatred", stats: parseStats("83 +17.5", "12 +2.5", "1.5 +0.15", "6.7 +0.67", "25 +5"), passive: "Burn Metal (+fire resist)", attribute: "+Str", effect: "DoT Amp (+DoT dmg)", proc: "Ember Proc (14% burn)", setBonus: "Flame Set (reflect on hit)" },
  { id: "metal-bloodfeud-feet", name: "Bloodfeud Feet", type: "Feet", material: "Metal", lore: "Forged in endless clan blood feuds", stats: parseStats("90 +19", "18 +3.5", "1.8 +0.18", "7.2 +0.72", "27 +5.4"), passive: "Tank Stance (+threat)", attribute: "+Vit", effect: "Armor Amp (+def)", proc: "Block Proc (20% reflect)", setBonus: "Guardian Set (AoE taunt)" },
  { id: "metal-wraithfang-feet", name: "Wraithfang Feet", type: "Feet", material: "Metal", lore: "Whispers forgotten grudges in the dark", stats: parseStats("85 +18", "23 +4.5", "2.8 +0.28", "6.7 +0.67", "26 +5.2"), passive: "Shadow Tank (+resist)", attribute: "+Str", effect: "Block Boost (+block dmg)", proc: "Wraith Proc (15% fear)", setBonus: "Phantom Set (absorb dmg)" },
  { id: "metal-oathbreaker-feet", name: "Oathbreaker Feet", type: "Feet", material: "Metal", lore: "Breaks ancient oaths of peace", stats: parseStats("95 +20", "13 +2.5", "0.8 +0.08", "7.7 +0.77", "28 +5.6"), passive: "Purge Metal (+cleanse)", attribute: "+Vit", effect: "Debuff Resist (+resist)", proc: "Oath Proc (18% purge)", setBonus: "Breaker Set (counter on block)" },
  { id: "metal-kinrend-feet", name: "Kinrend Feet", type: "Feet", material: "Metal", lore: "Rends bonds of blood and kinship", stats: parseStats("92 +19.5", "16 +3", "2.3 +0.23", "7.2 +0.72", "27.5 +5.5"), passive: "Blood Metal (+lifesteal)", attribute: "+Str", effect: "Heal Amp (+self heal)", proc: "Kin Proc (16% heal on block)", setBonus: "Family Set (group shield)" },
  { id: "metal-dusksinger-feet", name: "Dusksinger Feet", type: "Feet", material: "Metal", lore: "Sings of twilight and ending grudges", stats: parseStats("88 +18.5", "20 +4", "1.3 +0.13", "7 +0.7", "26.5 +5.3"), passive: "Twilight Metal (+speed)", attribute: "+Vit", effect: "Mobility Boost (+move)", proc: "Dusk Proc (13% speed burst)", setBonus: "Evening Set (AoE resist aura)" },
  { id: "metal-emberclad-feet", name: "Emberclad Feet", type: "Feet", material: "Metal", lore: "Clad in flames of burning hatred", stats: parseStats("93 +19.5", "15 +3", "1.8 +0.18", "7.4 +0.74", "27 +5.4"), passive: "Burn Metal (+fire resist)", attribute: "+Str", effect: "DoT Amp (+DoT dmg)", proc: "Ember Proc (14% burn)", setBonus: "Flame Set (reflect on hit)" },
  { id: "metal-bloodfeud-ring", name: "Bloodfeud Ring", type: "Ring", material: "Metal", lore: "Forged in endless clan blood feuds", stats: parseStats("50 +10.5", "10 +2", "1 +0.1", "4 +0.4", "15 +3"), passive: "Tank Stance (+threat)", attribute: "+Vit", effect: "Armor Amp (+def)", proc: "Block Proc (20% reflect)", setBonus: "Guardian Set (AoE taunt)" },
  { id: "metal-wraithfang-ring", name: "Wraithfang Ring", type: "Ring", material: "Metal", lore: "Whispers forgotten grudges in the dark", stats: parseStats("47.5 +10", "12.5 +2.5", "1.5 +0.15", "3.75 +0.375", "14.5 +2.9"), passive: "Shadow Tank (+resist)", attribute: "+Str", effect: "Block Boost (+block dmg)", proc: "Wraith Proc (15% fear)", setBonus: "Phantom Set (absorb dmg)" },
  { id: "metal-oathbreaker-ring", name: "Oathbreaker Ring", type: "Ring", material: "Metal", lore: "Breaks ancient oaths of peace", stats: parseStats("52.5 +11", "7.5 +1.5", "0.5 +0.05", "4.25 +0.425", "15.5 +3.1"), passive: "Purge Metal (+cleanse)", attribute: "+Vit", effect: "Debuff Resist (+resist)", proc: "Oath Proc (18% purge)", setBonus: "Breaker Set (counter on block)" },
  { id: "metal-kinrend-ring", name: "Kinrend Ring", type: "Ring", material: "Metal", lore: "Rends bonds of blood and kinship", stats: parseStats("51 +10.75", "9 +1.75", "1.25 +0.125", "4 +0.4", "15.25 +3.05"), passive: "Blood Metal (+lifesteal)", attribute: "+Str", effect: "Heal Amp (+self heal)", proc: "Kin Proc (16% heal on block)", setBonus: "Family Set (group shield)" },
  { id: "metal-dusksinger-ring", name: "Dusksinger Ring", type: "Ring", material: "Metal", lore: "Sings of twilight and ending grudges", stats: parseStats("49 +10.25", "11 +2.25", "0.75 +0.075", "3.9 +0.39", "14.75 +2.95"), passive: "Twilight Metal (+speed)", attribute: "+Vit", effect: "Mobility Boost (+move)", proc: "Dusk Proc (13% speed burst)", setBonus: "Evening Set (AoE resist aura)" },
  { id: "metal-emberclad-ring", name: "Emberclad Ring", type: "Ring", material: "Metal", lore: "Clad in flames of burning hatred", stats: parseStats("51.5 +10.75", "8.5 +1.75", "1 +0.1", "4.1 +0.41", "15 +3"), passive: "Burn Metal (+fire resist)", attribute: "+Str", effect: "DoT Amp (+DoT dmg)", proc: "Ember Proc (14% burn)", setBonus: "Flame Set (reflect on hit)" },
  { id: "metal-bloodfeud-necklace", name: "Bloodfeud Necklace", type: "Necklace", material: "Metal", lore: "Forged in endless clan blood feuds", stats: parseStats("50 +10.5", "10 +2", "1 +0.1", "4 +0.4", "15 +3"), passive: "Tank Stance (+threat)", attribute: "+Vit", effect: "Armor Amp (+def)", proc: "Block Proc (20% reflect)", setBonus: "Guardian Set (AoE taunt)" },
  { id: "metal-wraithfang-necklace", name: "Wraithfang Necklace", type: "Necklace", material: "Metal", lore: "Whispers forgotten grudges in the dark", stats: parseStats("47.5 +10", "12.5 +2.5", "1.5 +0.15", "3.75 +0.375", "14.5 +2.9"), passive: "Shadow Tank (+resist)", attribute: "+Str", effect: "Block Boost (+block dmg)", proc: "Wraith Proc (15% fear)", setBonus: "Phantom Set (absorb dmg)" },
  { id: "metal-oathbreaker-necklace", name: "Oathbreaker Necklace", type: "Necklace", material: "Metal", lore: "Breaks ancient oaths of peace", stats: parseStats("52.5 +11", "7.5 +1.5", "0.5 +0.05", "4.25 +0.425", "15.5 +3.1"), passive: "Purge Metal (+cleanse)", attribute: "+Vit", effect: "Debuff Resist (+resist)", proc: "Oath Proc (18% purge)", setBonus: "Breaker Set (counter on block)" },
  { id: "metal-kinrend-necklace", name: "Kinrend Necklace", type: "Necklace", material: "Metal", lore: "Rends bonds of blood and kinship", stats: parseStats("51 +10.75", "9 +1.75", "1.25 +0.125", "4 +0.4", "15.25 +3.05"), passive: "Blood Metal (+lifesteal)", attribute: "+Str", effect: "Heal Amp (+self heal)", proc: "Kin Proc (16% heal on block)", setBonus: "Family Set (group shield)" },
  { id: "metal-dusksinger-necklace", name: "Dusksinger Necklace", type: "Necklace", material: "Metal", lore: "Sings of twilight and ending grudges", stats: parseStats("49 +10.25", "11 +2.25", "0.75 +0.075", "3.9 +0.39", "14.75 +2.95"), passive: "Twilight Metal (+speed)", attribute: "+Vit", effect: "Mobility Boost (+move)", proc: "Dusk Proc (13% speed burst)", setBonus: "Evening Set (AoE resist aura)" },
  { id: "metal-emberclad-necklace", name: "Emberclad Necklace", type: "Necklace", material: "Metal", lore: "Clad in flames of burning hatred", stats: parseStats("51.5 +10.75", "8.5 +1.75", "1 +0.1", "4.1 +0.41", "15 +3"), passive: "Burn Metal (+fire resist)", attribute: "+Str", effect: "DoT Amp (+DoT dmg)", proc: "Ember Proc (14% burn)", setBonus: "Flame Set (reflect on hit)" },
  { id: "metal-bloodfeud-relic", name: "Bloodfeud Relic", type: "Relic", material: "Metal", lore: "Forged in endless clan blood feuds", stats: parseStats("50 +10.5", "10 +2", "1 +0.1", "4 +0.4", "15 +3"), passive: "Tank Stance (+threat)", attribute: "+Vit", effect: "Armor Amp (+def)", proc: "Block Proc (20% reflect)", setBonus: "Guardian Set (AoE taunt)" },
  { id: "metal-wraithfang-relic", name: "Wraithfang Relic", type: "Relic", material: "Metal", lore: "Whispers forgotten grudges in the dark", stats: parseStats("47.5 +10", "12.5 +2.5", "1.5 +0.15", "3.75 +0.375", "14.5 +2.9"), passive: "Shadow Tank (+resist)", attribute: "+Str", effect: "Block Boost (+block dmg)", proc: "Wraith Proc (15% fear)", setBonus: "Phantom Set (absorb dmg)" },
  { id: "metal-oathbreaker-relic", name: "Oathbreaker Relic", type: "Relic", material: "Metal", lore: "Breaks ancient oaths of peace", stats: parseStats("52.5 +11", "7.5 +1.5", "0.5 +0.05", "4.25 +0.425", "15.5 +3.1"), passive: "Purge Metal (+cleanse)", attribute: "+Vit", effect: "Debuff Resist (+resist)", proc: "Oath Proc (18% purge)", setBonus: "Breaker Set (counter on block)" },
  { id: "metal-kinrend-relic", name: "Kinrend Relic", type: "Relic", material: "Metal", lore: "Rends bonds of blood and kinship", stats: parseStats("51 +10.75", "9 +1.75", "1.25 +0.125", "4 +0.4", "15.25 +3.05"), passive: "Blood Metal (+lifesteal)", attribute: "+Str", effect: "Heal Amp (+self heal)", proc: "Kin Proc (16% heal on block)", setBonus: "Family Set (group shield)" },
  { id: "metal-dusksinger-relic", name: "Dusksinger Relic", type: "Relic", material: "Metal", lore: "Sings of twilight and ending grudges", stats: parseStats("49 +10.25", "11 +2.25", "0.75 +0.075", "3.9 +0.39", "14.75 +2.95"), passive: "Twilight Metal (+speed)", attribute: "+Vit", effect: "Mobility Boost (+move)", proc: "Dusk Proc (13% speed burst)", setBonus: "Evening Set (AoE resist aura)" },
  { id: "metal-emberclad-relic", name: "Emberclad Relic", type: "Relic", material: "Metal", lore: "Clad in flames of burning hatred", stats: parseStats("51.5 +10.75", "8.5 +1.75", "1 +0.1", "4.1 +0.41", "15 +3"), passive: "Burn Metal (+fire resist)", attribute: "+Str", effect: "DoT Amp (+DoT dmg)", proc: "Ember Proc (14% burn)", setBonus: "Flame Set (reflect on hit)" },
];

export const GEM_EQUIPMENT: EquipmentItem[] = [
  { id: "gem-bloodfeud-offhand", name: "Bloodfeud Gem", type: "Offhand", material: "Gem", lore: "Forged in endless clan blood feuds", stats: parseStats("30 +6", "100 +20", "7 +1.2", "0 +0", "10 +2"), passive: "Mana Gem (+mana regen)", attribute: "+Int", effect: "Spell Amp (+magic)", proc: "Mana Proc (12% restore)", setBonus: "Arcane Gem (group mana)" },
  { id: "gem-wraithfang-offhand", name: "Wraithfang Gem", type: "Offhand", material: "Gem", lore: "Whispers forgotten grudges in the dark", stats: parseStats("27 +5.5", "105 +21", "8 +1.4", "0 +0", "9 +1.8"), passive: "Shadow Gem (+stealth)", attribute: "+Wis", effect: "Evasion Boost (+dodge)", proc: "Shadow Proc (14% invis)", setBonus: "Wraith Gem (duplicate cast)" },
  { id: "gem-oathbreaker-offhand", name: "Oathbreaker Gem", type: "Offhand", material: "Gem", lore: "Breaks ancient oaths of peace", stats: parseStats("33 +6.5", "95 +19", "6 +1", "0 +0", "11 +2.2"), passive: "Purge Gem (+cleanse)", attribute: "+Int", effect: "Debuff Resist (+resist)", proc: "Oath Proc (18% purge)", setBonus: "Breaker Gem (amp on purge)" },
  { id: "gem-kinrend-offhand", name: "Kinrend Gem", type: "Offhand", material: "Gem", lore: "Rends bonds of blood and kinship", stats: parseStats("31 +6.25", "98 +19.5", "7.5 +1.25", "0 +0", "10.5 +2.1"), passive: "Blood Gem (+lifesteal)", attribute: "+Wis", effect: "Heal Amp (+healing)", proc: "Kin Proc (15% group heal)", setBonus: "Family Gem (shared heal)" },
  { id: "gem-dusksinger-offhand", name: "Dusksinger Gem", type: "Offhand", material: "Gem", lore: "Sings of twilight and ending grudges", stats: parseStats("29 +5.75", "102 +20.5", "6.5 +1.1", "0 +0", "9.5 +1.9"), passive: "Twilight Gem (+speed)", attribute: "+Int", effect: "Mobility Boost (+move)", proc: "Dusk Proc (11% teleport)", setBonus: "Evening Gem (AoE invis)" },
  { id: "gem-emberclad-offhand", name: "Emberclad Gem", type: "Offhand", material: "Gem", lore: "Clad in flames of burning hatred", stats: parseStats("33 +6.5", "97 +19.5", "6 +1", "0 +0", "10 +2"), passive: "Burn Gem (+fire resist)", attribute: "+Wis", effect: "DoT Amp (+DoT)", proc: "Ember Proc (13% burn)", setBonus: "Flame Gem (reflect fire)" },
];

export const ALL_EQUIPMENT = [
  ...CLOTH_EQUIPMENT,
  ...LEATHER_EQUIPMENT,
  ...METAL_EQUIPMENT,
  ...GEM_EQUIPMENT,
];

export function getEquipmentByMaterial(material: string): EquipmentItem[] {
  switch (material) {
    case "Cloth": return CLOTH_EQUIPMENT;
    case "Leather": return LEATHER_EQUIPMENT;
    case "Metal": return METAL_EQUIPMENT;
    case "Gem": return GEM_EQUIPMENT;
    default: return ALL_EQUIPMENT;
  }
}

export function getEquipmentByType(type: string): EquipmentItem[] {
  return ALL_EQUIPMENT.filter(e => e.type === type);
}

export function getEquipmentBySet(setName: string): EquipmentItem[] {
  return ALL_EQUIPMENT.filter(e => e.name.toLowerCase().includes(setName.toLowerCase()));
}

export function calculateStatsAtTier(item: EquipmentItem, tier: number): { hp: number; mana: number; crit: number; block: number; defense: number } {
  const tierBonus = tier - 1;
  return {
    hp: Math.round(item.stats.hpBase + (item.stats.hpPerTier * tierBonus)),
    mana: Math.round(item.stats.manaBase + (item.stats.manaPerTier * tierBonus)),
    crit: +(item.stats.critBase + (item.stats.critPerTier * tierBonus)).toFixed(1),
    block: +(item.stats.blockBase + (item.stats.blockPerTier * tierBonus)).toFixed(1),
    defense: Math.round(item.stats.defenseBase + (item.stats.defensePerTier * tierBonus)),
  };
}
